# General
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
max_width = 120

# Control Flow
fn_call_width = 60
match_block_trailing_comma = true

# Ordering
reorder_imports = true
reorder_modules = true

# Misc
use_try_shorthand = true
use_field_init_shorthand = true
